# Generated by Django 3.2.7 on 2021-10-01 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateActivity', models.CharField(max_length=50, verbose_name='Estado de Actividad')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionActivity', models.CharField(max_length=250)),
                ('observation', models.CharField(blank=True, max_length=100, verbose_name='Observación de Actividad')),
                ('assignmentDate', models.DateField(verbose_name='Fecha de Asignación')),
                ('estimatedTime', models.TimeField(verbose_name='Tiempo Estimado para la Tarea')),
                ('finishDate', models.DateField(verbose_name='Fecha de Finalización')),
                ('stateActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityToState', to='tareas.state', verbose_name='Estado de Actividad')),
                ('taskOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Tarea')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
